cabal-version:      2.4
name:               json-logic-hs
version:            0.1.0.0

-- A short (one-line) description of the package.
-- synopsis:

-- A longer description of the package.
-- description:

-- A URL where users can report bugs.
-- bug-reports:

-- The license under which the package is released.
-- license:
author:             piyushKumar-1
maintainer:         piyush.kumar@juspay.in

-- A copyright notice.
-- copyright:
-- category:
extra-source-files:
    CHANGELOG.md
    test/fixtures/congestion_old.json
    test/fixtures/congestion_new.json
    test/fixtures/congestion250_old.json
    test/fixtures/congestion250_new.json

common warnings
    default-language: Haskell2010
    ghc-options: -Wall -Wcompat -Widentities -fhide-source-paths -Werror

common extensions
    default-extensions:
      ConstraintKinds
      DataKinds
      DefaultSignatures
      DeriveAnyClass
      DeriveFunctor
      DeriveGeneric
      DuplicateRecordFields
      ExplicitNamespaces
      FlexibleContexts
      FlexibleInstances
      FunctionalDependencies
      GADTs
      LambdaCase
      MultiParamTypeClasses
      MultiWayIf
      NamedFieldPuns
      NoImplicitPrelude
      OverloadedStrings
      PatternSynonyms
      PolyKinds
      RankNTypes
      RecordWildCards
      ScopedTypeVariables
      TupleSections
      TypeApplications
      TypeFamilies
      TypeOperators
      ViewPatterns
      BlockArguments
      TypeSynonymInstances
      UndecidableInstances
      StandaloneDeriving
      PackageImports
      TemplateHaskell

common engine-deps
    build-depends:
      base
      , containers
      , aeson
      , vector
      , extra
      , scientific
      , text
      , exceptions
      , async
      , transformers
      , transformers-either
      , time

library
    import:           warnings, extensions, engine-deps
    hs-source-dirs:   app
    ghc-options:      -fwrite-ide-info -hiedir=.hie
    exposed-modules:
      JsonLogic
      JsonLogic.Runner

executable json-logic-hs
    import:           warnings, extensions, engine-deps
    hs-source-dirs:   app
    ghc-options:      -fwrite-ide-info -hiedir=.hie
    main-is:          Main.hs
    other-modules:    JsonLogic

test-suite json-logic-hs-test
    import:           warnings, extensions
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Spec.hs
    build-depends:
      base
      , aeson
      , vector
      , scientific
      , bytestring
      , json-logic-hs

executable jl-verify
    import:           warnings, extensions
    hs-source-dirs:   verify
    main-is:          Verify.hs
    build-depends:
      base
      , aeson
      , bytestring
      , vector
      , json-logic-hs
